### ISSUE TITLE
Idea: Grab and grabbing mouse for blocks

### ISSUE THREAD

**Issue by Daniel4-Scratch** [jmoenig/Snap#2700]
Grab and grabbing mouse for blocks, to tell the user that you can grab and you are grabbing this block. I think this would be a nice feature.
```css
#block:hover{
cursor: grab;
}
#block:active{
cursor: grabbing;
}
```
